### PR TITLE
not use babel-node in prod (+1 squashed commit)

### LINKED ISSUE #15: don't use babel-node in production
I see
```
    "start": "NODE_ENV=production babel-node ./api & node .",
```

babel-node isn't meant for production use as it's much less efficient. 
please correct me if I'm wrong, and happy to make PR.

### PR DESCRIPTION
**Pull request by frankleng**
resolves #15 

Squashed commits:
[22c3410] rename index.js to server.js

### CODE REVIEW

**Comment by faergeek** [comment]
What about not using `babel/register` as it transpiles in runtime too and instead transpile before run?
Like that:

```
"build:api": "babel api > api/index.es5.js",
"build": "npm run build:server && npm run build:client && npm run build:api",
"start": "node ./api/index.es5.js & node .",
```

**Comment by olegakbarov** [comment]
Yeah, if we target `production` — it is better to have pre-compiled es5.

**Comment by frankleng** [comment]
No need as far as I can tell. It's not transpiled on every user request if that's what you meant.

The register hook maintains its own cache in a local json file. It basically replaces node's require(), which also isn't executed on every user request.

**Comment by faergeek** [comment]
I mean that it looks like we get almost the same result
https://github.com/babel/babel/blob/master/packages/babel-cli/src/_babel-node.js

Would be better to transpile before run and not install `babel` in production at all.

**Comment by frankleng** [comment]
Would that make debugging on prod more difficult? transpiled code isn't always that readable.

**Comment by faergeek** [comment]
You don't need to read transpiled code, we should use sourcemaps for that.

**Comment by faergeek** [comment]
Thanks for pointing at this, but we'll fix it another way.

**Pull request closed without merging**
